# Github workflow to build and test the Nexus Toolkit for Rust code

name: Nexus Toolkit for Rust
on:
  pull_request:
    paths:
      - "toolkit-rust/**"
      - ".github/workflows/toolkit-rust.yml"
  push:
    branches:
      - main
    paths:
      - "toolkit-rust/**"
      - ".github/workflows/toolkit-rust.yml"

jobs:
  # 1. Install Rust
  # 2. Install Rust cache
  # 3. Install just
  # 4. Build, fmt, clippy and test the Toolkit for Rust
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # 1.
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # 2.
      - name: Cache Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: toolkit-rust

      # 3.
      - uses: taiki-e/install-action@just

      # 4
      - run: just toolkit-rust check
      - run: just toolkit-rust fmt-check
      - run: just toolkit-rust clippy
      - run: just toolkit-rust test
